TESTING|allow bypassing locks if the lock holder is the same as the previous

diff --git a/.github/workflows/mercury_bot.yml b/.github/workflows/mercury_bot.yml
--- a/.github/workflows/mercury_bot.yml
+++ b/.github/workflows/mercury_bot.yml
@@ -69,6 +69,11 @@ jobs:
             const effectivelyNew = ownersFile.status == 'added' || ownersFile.status == 'renamed';
             console.log(`setting output: net-new-owners-file=${effectivelyNew}`);
             core.setOutput('net-new-owners-file', effectivelyNew);
+            core.setOutput('is-rename', ownersFile.status == 'renamed')
+            if (ownersFile.status === 'renamed') {
+              core.setOutput('previous-filename', ownersFile.previous_filename);
+            }
+
 
       # Only used to assert content of the OWNERS file.
       - name: Checkout Pull Request
@@ -121,6 +126,23 @@ jobs:
         with:
           chart-name: ${{ steps.check_for_owners.outputs.chart-name }}
           fail-workflow-if-locked: 'false'
+        
+      # Rename operations would produce a locking failure because main has an
+      # existing lock. For renaming operations, look at the locking failure
+      # closely and determine if they're related or not.
+      - name: Asserting rename does not trample unrelated lock
+        id: check-lock-relation
+        if: |
+          steps.populate-file-mod-type.outputs.is-rename
+          && steps.determine-lock-status.outputs.chart-is-locked == 'true'
+        env:
+          PREVIOUS_FILENAME: ${{ steps.populate-file-mod-type.outputs.previous-filename && steps.populate-file-mod-type.outputs.previous-filename || 'unset' }}
+          CURRENT_LOCK: join(['charts', steps.determine-lock-status.outputs.locked-to-path], '/')
+          LOCKED_TO_PREVIOUS: ${{ steps.populate-file-mod-type.outputs.previous-filename && steps.populate-file-mod-type.outputs.previous-filename || 'unset' }} == join(['charts', steps.determine-lock-status.outputs.locked-to-path], '/')
+        run: |
+          echo "Current lock is set to ${CURRENT_LOCK}"
+          echo "The previous filename for this rename is: ${PREVIOUS_FILENAME}"
+          echo locked-to-previous-filename="${LOCKED_TO_PREVIOUS}" | tee -a $GITHUB_OUTPUT
 
       # Do not merge net-new OWNERS files for locked chart names. Allow a
       # modification to an existing file. The mercury-bot periodically updates
@@ -130,7 +152,8 @@ jobs:
         env:
           NET_NEW_OWNERS_FILE: ${{ steps.populate-file-mod-type.outputs.net-new-owners-file }}
           CHART_IS_LOCKED: ${{ steps.determine-lock-status.outputs.chart-is-locked }}
-          MERGE_PR: ${{ steps.populate-file-mod-type.outputs.net-new-owners-file == 'false' || (steps.populate-file-mod-type.outputs.net-new-owners-file == 'true' && steps.determine-lock-status.outputs.chart-is-locked == 'false') }}
+          CHART_LOCKED_TO_PREVIOUS: ${{ steps.determine-lock-status.outputs.chart-is-locked == 'true' && steps.check-lock-relation.outputs.locked-to-previous-filename == 'true' }}
+          MERGE_PR: ${{ steps.populate-file-mod-type.outputs.net-new-owners-file == 'false' || (steps.populate-file-mod-type.outputs.net-new-owners-file == 'true' && (steps.determine-lock-status.outputs.chart-is-locked == 'false' || (steps.determine-lock-status.outputs.chart-is-locked == 'true' && steps.check-lock-relation.outputs.locked-to-previous-filename == 'true'))) }}
         run: |
           echo "OWNERS file is net new: ${NET_NEW_OWNERS_FILE}"
           echo "Chart name is already locked: ${CHART_IS_LOCKED}"
